# Generated by Django 2.1.4 on 2020-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jinhuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True, verbose_name='服装款号')),
                ('sort', models.CharField(max_length=6, verbose_name='类别')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='进货时间')),
                ('total', models.CharField(max_length=4, verbose_name='进货总数')),
            ],
            options={
                'verbose_name': '进货',
                'verbose_name_plural': '进货',
                'ordering': ['-c_time'],
            },
        ),
    ]
