# Generated by Django 2.1.4 on 2020-04-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jinhuo',
            name='l_total',
            field=models.IntegerField(default=0, max_length=4, verbose_name='L号的总数'),
        ),
        migrations.AddField(
            model_name='jinhuo',
            name='m_total',
            field=models.IntegerField(default=0, max_length=4, verbose_name='M号的总数'),
        ),
        migrations.AddField(
            model_name='jinhuo',
            name='xl_total',
            field=models.IntegerField(default=0, max_length=4, verbose_name='XL号的总数'),
        ),
        migrations.AddField(
            model_name='jinhuo',
            name='xxl_total',
            field=models.IntegerField(default=0, max_length=4, verbose_name='2XL号的总数'),
        ),
        migrations.AddField(
            model_name='jinhuo',
            name='xxxl_total',
            field=models.IntegerField(default=0, max_length=4, verbose_name='3XL号的总数'),
        ),
        migrations.AddField(
            model_name='jinhuo',
            name='xxxxl_total',
            field=models.IntegerField(default=0, max_length=4, verbose_name='4XL号的总数'),
        ),
        migrations.AlterField(
            model_name='jinhuo',
            name='total',
            field=models.IntegerField(default=0, max_length=6, verbose_name='进货总数'),
        ),
    ]
