# Generated by Django 2.1.4 on 2020-04-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_kucun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jinhuo',
            name='number',
            field=models.CharField(max_length=12, verbose_name='服装款号'),
        ),
        migrations.AlterField(
            model_name='kucun',
            name='number',
            field=models.CharField(max_length=12, verbose_name='服装款号'),
        ),
        migrations.AlterField(
            model_name='xiaoshou',
            name='number',
            field=models.CharField(max_length=12, verbose_name='服装款号'),
        ),
    ]
