# Generated by Django 2.1.4 on 2020-04-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200424_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='fanhuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='商品款号')),
                ('sort', models.CharField(max_length=10, verbose_name='商品名称')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='返货调货时间')),
                ('m_total', models.IntegerField(default=0, verbose_name='M')),
                ('l_total', models.IntegerField(default=0, verbose_name='L')),
                ('xl_total', models.IntegerField(default=0, verbose_name='XL')),
                ('xxl_total', models.IntegerField(default=0, verbose_name='2XL')),
                ('xxxl_total', models.IntegerField(default=0, verbose_name='3XL')),
                ('xxxxl_total', models.IntegerField(default=0, verbose_name='4XL')),
                ('color', models.CharField(max_length=6, null=True, verbose_name='颜色')),
                ('total', models.IntegerField(default=0, verbose_name='库存总数')),
                ('price', models.IntegerField(default=0, verbose_name='单价')),
                ('price_total', models.IntegerField(default=0, verbose_name='总价')),
                ('tips', models.CharField(max_length=8, verbose_name='备注')),
            ],
            options={
                'verbose_name': '返货',
                'verbose_name_plural': '返货',
                'ordering': ['-c_time'],
            },
        ),
    ]
