# Generated by Django 2.1.4 on 2020-04-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_fanhuo'),
    ]

    operations = [
        migrations.CreateModel(
            name='vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='会员手机号')),
                ('name', models.CharField(max_length=5, verbose_name='会员名字')),
                ('jifen_total', models.IntegerField(default=0, verbose_name='总积分')),
                ('jifen_history', models.IntegerField(default=0, verbose_name='历史消费总积分')),
                ('yucun', models.IntegerField(default=0, verbose_name='预存总金额')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '会员积分',
                'verbose_name_plural': '会员积分',
                'ordering': ['-c_time'],
            },
        ),
    ]
