# Generated by Django 2.1.4 on 2020-04-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='yucun_total',
            field=models.IntegerField(default=0, verbose_name='预存总次数'),
        ),
    ]
