# Generated by Django 2.1.4 on 2020-04-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_vip_yucun_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='vip_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='会员手机号')),
                ('name', models.CharField(max_length=5, verbose_name='会员名')),
                ('jifen_use', models.IntegerField(default=0, verbose_name='兑换积分')),
                ('jifen_get', models.IntegerField(default=0, verbose_name='单次获得积分')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '会员详情',
                'verbose_name_plural': '会员详情',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='vip',
            options={'ordering': ['-c_time'], 'verbose_name': '会员积分管理', 'verbose_name_plural': '会员积分管理'},
        ),
    ]
