# Generated by Django 2.1.4 on 2021-03-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanhuo',
            name='shop_name',
            field=models.CharField(max_length=10, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='jinhuo',
            name='shop_name',
            field=models.CharField(max_length=10, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='kucun',
            name='shop_name',
            field=models.CharField(max_length=10, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='vip',
            name='shop_name',
            field=models.CharField(max_length=10, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='vip_detail',
            name='shop_name',
            field=models.CharField(max_length=10, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='xiaoshou',
            name='shop_name',
            field=models.CharField(max_length=10, null=True, verbose_name='店名'),
        ),
    ]
